//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Major { get; set; }
        public string Seniority { get; set; }
        public string Interests { get; set; }
        public string EntryDate { get; set; }
    
        public virtual Major Major1 { get; set; }
        public virtual Nationality Nationality1 { get; set; }
    }
}
